Review/hw 02
Ranihilator/projects_for_home_work pull request #6
Opened 2018-08-01 16:08 UTC by Ranihilator

Review

2018-08-02 23:04 UTC, ithamsteri requested changes
Программа работает корректно, но:
* необходимо разобраться с "Наследование vs. Композиция";
 * избавиться от rvalue ссылки при передаче аргумента в функцию `split_ip`;
 * пересмотреть обработку исключений.
 * исправить тесты в соответствии с условием задания.

2018-08-03 05:16 UTC, Ranihilator reviewed
Структуру превращу в класс и сделаю наследование приватным.

теперь сылка в spilt_ip константная

С исключением подумаю, как его использовать

Внесу в работу regex дополнительную проверку, чтобы он не начинал работу в поиске ип адресса, если первое вхождения символа является мусор

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/CMakeLists.txt
> +    set(VERSION_BUILD_MAJOR 1)
Убрал повторы

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/CMakeLists.txt
> +  COMPILE_OPTIONS -Wpedantic -Wall -Wextra
Пока убрал флаги, они тут ненужны. подумаю над решением проверки компилятора

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/CMakeLists.txt
> +  INCLUDE_DIRECTORIES ${Boost_INCLUDE_DIR}
Теперь буду знать, удобно

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/CMakeLists.txt
> +target_link_libraries(ip_filter
Убрал

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/CMakeLists.txt
> +target_link_libraries(ip_filter_testing
Оптимизировал

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/include/filter.h
> +	out << (int)std::get<0>(ip) << "."
Подумаю над реализации, пока оставлю так

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/include/filter.h
> +struct IP_Address_Sort: public std::deque<ip_address>
Согласен, получается структура будет очень перегружена открытыми методами и прочим мусором из std::deque и на фоне всего этого свои методы будут теряться, особенно в IDE с подсказками.

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/include/filter.h
> +auto split_ip(std::string &&line, std::regex &filter)
Не знал, что константная ссылка позволит передавать lvalue и rvalue, из за этого и использовал rvalue ссылку. Исправил

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/src/main.cpp
> +		catch (std::invalid_argument &e) {}
Согласен исключение, лишняя трата ресурсов.

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/src/main.cpp
> +	for (auto &i : data)
Согласен, тут можно сделать лучше

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/test/test.cpp
> +auto random_test(std::string left_dust = std::string(), std::string right_dust = std::string())
Забыл грохнуть старый код

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/test/test.cpp
> +	BOOST_CHECK(split_ip("7 3 1garbage 127.0.0.25 garbage 1 2 6 1",ip_filter) == std::make_tuple(127,0,0,25));
это особенность работы regex, по сути он из кучи мусора мне выдал первое вхождение ип адресса. Подумаю над правкой синтаксиса regex маски

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/test/test.cpp
> +BOOST_AUTO_TEST_CASE(filter_test)
Согласен

2018-08-03 05:16 UTC, Ranihilator commented on hw_02/test/test.cpp
> +	return (c >= 0) ? ((x <= t) ? (bin_id(x, t >> 1, --c)) : (c)) : (0);
Красота!

2018-08-03 09:29 UTC, ithamsteri submitted a review, later dismissed
Исполнитель исправил rvalue ссылку у аргумента функции. Улучшил `CMakeLists.txt`. Хотя осталось исправить тесты, где не верно тестируются входные данные.

2018-08-05 09:49 UTC, pk-otus commented on hw_02/CMakeLists.txt
> +  COMPILE_OPTIONS -Wpedantic -Wall -Wextra
Согласен, проверку можно сделать, например, такую:
`if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
`else()
'endif()

2018-08-05 11:09 UTC, pk-otus commented on hw_02/test/test.cpp
> +	return (c >= 0) ? ((x <= t) ? (bin_id(x, t >> 1, --c)) : (c)) : (0);
А разве можно добавлять собственные параметры в сигнатуру? Там, конечно, стояла какая то подозрительная запятая, но всё же? Вот было у меня 
`auto x = std::pow(2,7);`
и я подумал: вот, как раз у меня constexpr степень двойки есть, и поменял:
`auto x = bin_id(2,7);`
что тогда? никакой ошибки не будет...

Я реализовал так:
```
	constexpr size_t bin_id(size_t x)
	{
		size_t y = 1;
		for(size_t i = 0; i < 8 * sizeof(size_t); ++i)
		{
			if (y >= x) return i;
			y *= 2;
		}
		return 8 * sizeof(size_t);
	}	
```

2018-08-05 11:31 UTC, pk-otus commented on hw_02/include/filter.h
> +}
По-хорошему, всю реализацию нужно вынести в cpp-файл, а в header оставить только структуру классов

2018-08-05 19:53 UTC, pk-otus commented on hw_02/include/filter.h
> +			if ( (std::get<0>(val) == N0 || N0 < 0) && (std::get<1>(val) == N1 || N1 < 0) && (std::get<2>(val) == N2 || N2 < 0) && (std::get<3>(val) == N3 || N3 < 0))
да, длинные строки очень плохо читаются

2018-08-06 06:50 UTC, pk-otus commented on hw_02/include/filter.h
> +	const int N0, N1, N2, N3;
Такого не должно встречаться, это "антипаттерн". Как минимум, это должен быть массив, вектор, кортеж и т.д.
А по факту, у тебя похожие структуры в коде уже есть (`ip_address`), можно использовать их, или сделать новый псевдоним, оставив ту же сущность.

2018-08-06 16:49 UTC, Ranihilator reviewed
Убраны магические константы.
Максимально использую ip_address тип
Уменьшена связность у классов сортировки
Небольшой рефакторинг

2018-08-06 16:49 UTC, Ranihilator commented on hw_02/include/filter.h
> +struct IP_Address_Sort: public std::deque<ip_address>
Уменьшил связность

2018-08-06 16:49 UTC, Ranihilator commented on hw_02/include/filter.h
> +	IP_Address_Sort(const int n0 = -1, const int n1 = -1, const int n2 = -1, const int n3 = -1):
Убрал числа

2018-08-06 16:49 UTC, Ranihilator commented on hw_02/include/filter.h
> +	auto operator<<(const ip_address& val)
Согласен можно использовать полиморфизм, возвращаемое значение не используется.

2018-08-06 16:49 UTC, Ranihilator commented on hw_02/include/filter.h
> +	auto operator<<(const ip_address& val)
Значит делаем полиморфизм =)

2018-08-07 05:49 UTC, pk-otus approved these changes

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
>  #include <algorithm>
`#include <sstream>`

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +
Проще T[4], или std::array<T,4>, а точнее 
`const size_t NUM_OCTETS = 4;`
`std::array<T,NUM_OCTETS>`
И лучше всё-таки отдельный псевдоним для маски фильтра, т.к. это разные сущности, хоть и с одинаковой структурой данных

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +};
не те константы. А если октетов станет 100? Просто сохрани максимальное количество в NUM_OCTETS, и сделай цикл от 0 до NUM_OCTETS

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +		<< static_cast<int>(std::get<FOUR_OCTER>(ip)) << std::endl;
вот тут, как раз, и должен быть цикл

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +					):
даже инициализатор приуныл от такого конструктора ))
какой смысл в значениях по умолчанию? ты всё равно не сможешь отфильтровать, например, по 3 байту отдельно.
Можно наворотить builder со значениями по умолчанию, о котором нам вчера рассказывал Сергей, или еще что-то придумать. По факту ты всё равно передаешь tuple<T,T,T,T>, просто в неявном виде, что усложняет и использование и чтение и сопровождение кода...

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +			std::get<FOUR_OCTER>(this->N) == ANY_OCTET
`this->N` - лишнее, можно просто N.
А вообще, это должен быть цикл от 0 до NUM_OCTETS

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +				)
и здесь цикл

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +				this->address.insert(val);
this тоже не нужен

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +		return stream;
верни сразу `stream.str()`
зачем заказчику знать, как ты реализовал вывод данных в строку? ему просто нужна строка.
Тот же TDA

P.S. это уже на правах IMHO, но мне не нравится auto как тип возвращаемого значения функции. Он выдает меньше ошибок и поэтому с ним легче запутаться и вернуть что-то не совсем корректное, как в этом примере. Я бы указывал типы возвращаемых значений явно.

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +
как же в одной структуре оказались `ip_address<int16_t>` и `ip_address<uint8_t>` (строка 122)? что то пошло не так...
Размер октета(ну или уже не октета) должен стать параметром шаблона

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +	std::multiset<ip_address<uint8_t>, std::greater_equal<ip_address<uint8_t>>> address;
multiset тут лишний. Ты требуешь, чтобы данные всегда были отсортированы. Всегда. После каждой вставки одного элемента. Лучше просто сделать вектор. И отсортируешь их один раз, перед фильтрацией.
Вставка с сортировкой очень медленна.

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +	auto dump()
повтор строки 110
Может, вынести этот код в отдельную функцию - не член класса?

2018-08-07 05:49 UTC, pk-otus commented on hw_02/include/filter.h
> +								);
здесь должен быть цикл

2018-08-07 05:49 UTC, pk-otus commented on hw_02/src/main.cpp
> +			data_filter_task1 << value;
сохраняешь одно и то же в 4 местах, плюс каждая из 4 вставок сопровождается пересортировкой.
Не особо быстро будет ))
Сделай, как и просили, фильтр: 
1. есть один набор исходных данных 
2. потом он сортируется
3. по сортированным данным делается один проход на предмет совпадения с фильтром. В случае совпадения результаты копируются в новый контейнер

2018-08-07 05:49 UTC, pk-otus commented on hw_02/src/main.cpp
> +	std::cout << data.dump().str();
После того, как функция dump будет возвращать std::string, получится:
`std::cout << data.dump();`

2018-08-07 09:45 UTC, Ranihilator commented on hw_02/include/filter.h
> +		<< static_cast<int>(std::get<FOUR_OCTER>(ip)) << std::endl;
Идею понял с циклом

2018-08-07 10:03 UTC, Ranihilator reviewed
Тест, частичные изменения

2018-08-07 10:03 UTC, Ranihilator commented on hw_02/include/filter.h
> +				this->address.insert(val);
this тут играет стилистическую роль. тем самым я помечаю для себя, что метод или переменная находится внутри класса а не где то снаружи.

2018-08-07 10:03 UTC, Ranihilator commented on hw_02/include/filter.h
> +
а это как раз маска, из за значения "-1" мне и пришлось сменить тип

2018-08-07 10:08 UTC, pk-otus commented on hw_02/include/filter.h
> +				this->address.insert(val);
а это не метод, это обращение к данным, а данные по определению внутри класса

2018-08-07 10:09 UTC, pk-otus commented on hw_02/include/filter.h
> +
вот вот, последствия отсутствия псевдонима и наличия "магической" -1

2018-08-07 10:11 UTC, pk-otus approved these changes

2018-08-09 10:31 UTC, ithamsteri requested changes
Требуется избавиться от строгой привязки к 4 октетам адреса и сделать код более универсальным. Предлагаю использовать Variadic Templates для этого вместо циклов.

2018-08-09 10:31 UTC, ithamsteri commented on hw_02/include/filter.h
> +				this->address.insert(val);
Соглашусь с @Ranihilator, т.к. без `this` он всё равно используется не явно. Это относится больше к стилю кода.

2018-08-09 10:31 UTC, ithamsteri commented on hw_02/include/filter.h
> +};
Очень будет полезно не привязываться к количеству октетов, т.к. этот код может пригодится для обработки IPv6 в дальнейшем и будет более универсальным.

2018-08-09 10:31 UTC, ithamsteri commented on hw_02/include/filter.h
> +		<< static_cast<int>(std::get<FOUR_OCTER>(ip)) << std::endl;
Соглашусь, что нужен цикл для универсальности.

2018-08-27 04:01 UTC, Ranihilator commented
Потребуется переработать полностью приложение.

2018-09-10 16:26 UTC, Yukigaru commented on hw_02/include/filter.h
> +	out << (int)std::get<0>(ip) << "."
несколько раз думал о том, нужно ли вводить поддержку и ipv4 и ipv6 одним классом, и не уверен, что это необходимо, т.к. для разных протоколов скорее всего используются даже разные драйвера и разные вызовы системных ф-ций.
имхо. пока не напишешь реальную программу, работающую с ipv6, не ясно

2018-09-10 16:32 UTC, Yukigaru commented on hw_02/src/main.cpp
> +	for (auto &i : data)
Наблюдатель в данном случае будет overengineering. Это же простая обработка последовательностей, кому-то что-то наблюдать в данной задаче не является необходимым.

2018-09-10 16:33 UTC, Yukigaru commented on hw_02/src/main.cpp
> +		catch (std::invalid_argument &e) {}
Согласен с pk-otus, лучше везде писать единнообразно (выбрана модель исключений, так её и используй), а pair с результатом ф-ции - довольно неудобно использовать.

2018-09-10 16:37 UTC, Yukigaru commented
Изучил ревью от Яшкина Александра (ithamsteri) для Ranihilator. Очень грамотное, детальное и хорошее ревью, приятно читать.

- внимательно проревьювил в том числе cmakelists и тесты
- делал замечания, как по вопросам использования C++, так и в вопросах проектирования классов
- форматировал свой ответ: использовал bold, добавлял ссылки и оборачивал код
- не поленился сделать несколько проверок после изменений в коде
- были места, где я не был согласен с ревьювером, либо по теме было что обсудить. Оставил свои комментарии.

2018-09-11 05:37 UTC, 0xck commented
Прочел замечания и предложения обоих ревьюверов. Первое что бросается в глаза это большой объем проделаной работы для ревью. Все замечания по существу. Комментарии снабжены альтернативными предложениями, примерами и пояснениями. Замечательная работа.

Исполнитель так же проделал дополнительную работу по устранению ряда проблемных и спортных мест кода.

2019-01-22 04:25 UTC, closed without merging