Review/hw 04
Ranihilator/projects_for_home_work pull request #8
Opened 2018-08-14 15:40 UTC by Ranihilator

Ревью печать ип адресса

2018-08-20 17:38 UTC, antik9 reviewed
Вообще хотелось бы отметить объем проделанной работы. Придраться сильно было не к чему. Я от себя могу сказать, что писал далеко не так качественно.

Есть пару мест с вопросами, но там ниже по комментариям. В целом очень хорошо. Объем просто поражает, конечно)

2018-08-20 17:38 UTC, antik9 commented on hw_04/CMakeLists.txt
> +set_property(TARGET version_lib PROPERTY IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../build/hw_01/libhelloworld_lib.a)
Это версия берется из первой домашки?) Остроумно, но получается, что постоянно деплоишь все домашки при перезаливке? И версия вы
Это скорее вопрос, чем замечение. Travis build к концу курсу будет минут 30 занимать, наверное?)

2018-08-20 17:38 UTC, antik9 commented on hw_04/README.md
> +Application print ip address
Сам я ленюсь писать README, в остальных ревью тоже не сильно этого замечал, так что круто. Возможно, немного читателей именно на этот рид, но я бы это точно отметил как плюс. Кто не любит README?

2018-08-20 17:38 UTC, antik9 commented on hw_04/include/print.h
> +>
Опять же приходится говорить про то, что нравится.
Данный шаблон выглядит очень правильно и элегантно.
с++ тебе.

2018-08-20 17:38 UTC, antik9 commented on hw_04/include/print.h
> +print_ip (const T arg, bool is_first = true)
Я ратую всегда за самодокументируемый код, в данном случае у нас на вход как минимум поступает контейнер. Так что почему не назвать переменную каким-то говорящим именем?

2018-08-20 17:38 UTC, antik9 commented on hw_04/include/tuple.h
> +			buffer << "..";
Сорри, сейчас нет возможности запустить и проверить. Тут две точки это зачем?

2018-08-20 17:38 UTC, antik9 commented on hw_04/include/tuple.h
> +{
В целом, эталонный tuple print наверное делается через index_sequence, так что оставлю тут это как заметку и себе, и тебе.
Этот же код читается немного сложновато. В следующий раз можно попробовать именно так и сделать.

2018-08-20 17:38 UTC, antik9 commented on hw_04/test/test.cpp
> +{
Я сам обычно пишу с Google Test, но у кого-то я видел capture c boost. 
Разве его нет по умолчанию в пакете? Или задумка была именно в удобстве для тестирования. Тогда плюс. Но с другой стороны использование уже проверенных инструментов в тестах гораздо надежнее. Определять что-то внутри хотелось бы по минимуму. Вдруг где-то там закрадется ошибка?

2018-08-20 17:38 UTC, antik9 commented on hw_04/test/test.cpp
> +		"256..4096..8192..2048..128..-1..-256..-1024..-4096..-8192\n"
В целом вопрос про ".." остался. В чем причина именно такого вывода?
Тестов много, даже не представляю как хватило сил все это написать и сделать.
Проблем в них, кроме вот этого непонятного места не вижу.

2018-08-21 02:45 UTC, Ranihilator commented on hw_04/CMakeLists.txt
> +set_property(TARGET version_lib PROPERTY IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/../build/hw_01/libhelloworld_lib.a)
Верно, все домашки собираются каждый коммит.
Минут 15, но тут больше не из за самой домашки, сколько всякая ерунда в него ставиться сторонняя.

2018-08-21 02:47 UTC, Ranihilator commented on hw_04/include/print.h
> +print_ip (const T arg, bool is_first = true)
Согласен, переменная должна отражать свой функционал по имени.

2018-08-21 02:48 UTC, Ranihilator commented on hw_04/include/tuple.h
> +			buffer << "..";
У меня такое условие домашки. Выводить через 2 точки

2018-08-21 02:49 UTC, Ranihilator commented on hw_04/test/test.cpp
> +{
Не изучал вопрос, исследую

2018-08-21 02:52 UTC, Ranihilator commented on hw_04/test/test.cpp
> +		"256..4096..8192..2048..128..-1..-256..-1024..-4096..-8192\n"
Что-то меня это настараживает =), у меня задания реально требует вывод "..".

2018-08-21 02:53 UTC, Ranihilator commented on hw_04/README.md
> +Application print ip address
Практикую скажем так английским =)

2018-08-21 04:07 UTC, antik9 commented on hw_04/include/tuple.h
> +			buffer << "..";
Это адская формулировка просто. Смотри. "Выводится содержимое поэлементно и
разделяется .. Опционально."
С точки зрения русского языка это звучит бессмысленно) Трактовать можно и как ты, и как я, и я даже не могу сам теперь понять как правильно. Но вообще если поставить кавычки, то я читал это так : 
"Выводится содержимое поэлементно и
разделяется '.'. Опционально." 
Может я и не прав.  ¯\_(ツ)_/

2018-08-21 07:49 UTC, Ranihilator commented on hw_04/include/tuple.h
> +			buffer << "..";
Я согласен, первые версии были с одной точкой. Но мне когда Василий проверял ДЗ сказал чтобы я не внимательно читал ДЗ, т.к. вывод требуется через ".." в итоге я переделал ДЗ была принята. Такие вот дела =)

2018-08-23 17:36 UTC, Ranihilator commented
_Ревью с предыдущего потока_

[**Ревьюер: Кирюшин Денис**
](https://github.com/slonegd)
**тесты**

1. отсутствуют тесты с отрицательными значениями чисел
2. разделение двумя точками в тестах с контейнерами .. такого в задании не было
3. в тестах с контейнерами появились отрицательные значения, которые выводятся как есть - отрицательными. Это противоречит заданию, в котором был пример для проверки ip от -1: должно выводится как 255
4. [/// Test tuple with long elements](https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/test/test.cpp#L609) Комментарий не соответствует тесту, в котором часть элементов tuple строки

**реализация**

1. enable_if_t по умолчанию имеет вторым параметром void, соответственно его можно не указывать.
2. [print_ip (const T arg, bool is_number = true) ](https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h#L40)не ясна необходимость во втором параметре функции
3. [print_ip (const T arg, bool new_line = true)](https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h#L80) в реализации для строки второй параметр понятен, но почему такого нет в реализации для чисел?
4. реализация для вектора и листа будет работать только со стандартным аллокатором
5. функция печати для tuple требует указать размер tuple в качестве шаблонного параметра. Рекомендую сделать функцию, которая принимает только tuple, а внутри неё вызвать уже имеющуюся функцию, которой передать размер.

2018-08-23 17:42 UTC, Ranihilator commented
_Ревью с предыдущего потока_

**Ревьюер: Невзоров Владимир**

**Критерии**:
1. Читаемость, сложность понимания кода
2. Соответствие заданию в части реализации одной шаблонной функцией с частичной специализацией.
3. Дублирование кода, т.е. неоднократное написание одного и того же кода в разных частях программы.
4. Покрытие тестами требуемого функционала

**Реализация**
Код читаемый, хорошо оформлен и структурирован. В значительной степени присутствуют комментарии.
Для реализации специализаций шаблонной функции выбран std::decay, благодаря которому код читается легко.
В некоторых функциях [поехали фигурные скобки](https://www.google.com/url?q=https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h%23L57&sa=D&ust=1535047984733000&usg=AFQjCNGyGcPybZDiofYYLfkUgP67PApGng). Можно улучшить форматирование.
Возможно, для удобства чтения не стоит увеличивать количество строк в конструкции [enable_if_t](https://www.google.com/url?q=https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h%23L57&sa=D&ust=1535047984733000&usg=AFQjCNGyGcPybZDiofYYLfkUgP67PApGng), и заменить 4 строчки одной:
<is_integral<typename std::decay<T>::type>::value, void>
Также вопрос дело вкуса использование class или typename в типе шаблона.
Быть может, typename окажется более предпочтительным в контексте решения данной задачи.
Присутствует оригинальное использование собственного пространства имен, внутри которого используется [namespace std](https://www.google.com/url?q=https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h%23L35&sa=D&ust=1535047984732000&usg=AFQjCNGdLfCPkS0xq-hFlZcioPv8wvdH_Q).
Кажется необычным использование [второго параметра](https://www.google.com/url?q=https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h%23L80&sa=D&ust=1535047984735000&usg=AFQjCNHQSR8Nj660YjnDhmfuTZdi85-tsA) по умолчанию для дополнительного вывода символа конца строки. Параметр при вызовах функций нигде не задается.

[Специализация функции ](https://www.google.com/url?q=https://github.com/Ranihilator/projects_for_home_work/blob/75ad865978c1f60fe9bc5b673c986a5ae78e7fc1/hw_04/include/print.h%23L40&sa=D&ust=1535047984731000&usg=AFQjCNFxweOiNPMw7E5PVzgLvG7D6pdhBQ)для интегральных типов вызывает некоторые вопросы:
- Зачем нужен параметр по умолчанию? 
- Почему при вызове он нигде не задается?
- Можно ли и имеет ли смысл проверку размера внутри функции static_assert(size > 0, "T must be > 0"); вынести каким-то образом в объявление - в enable_if_t<...> 

Положительные моменты реализации:
- Активно используется приведение в С++ стиле -  static_cast<...>(...); 
- Реализован опциональный функционал - специализация функции для tuple.
- Реализация специализации функции для контейнеров позволяет выводить контейнер контейнеров.
- Используется короткая запись - enable_if_t

**Тесты**
Присутствуют многочисленные тесты практически на все возможные варианты использования функций. 
Не увидел тест на проверку функции с отрицательным интегральным типом:
print_ip(static_cast<uint8_t>(-1));

**Соответствие критериям ревью**
1. Код читаемый, понятный.
2. Реализация соответствует заданию.
3. Дублирования кода не встретил.
4. Тесты полностью покрывают требуемый в задании функционал.

2018-08-23 17:46 UTC, Ranihilator commented on hw_04/test/test.cpp
> +	/// Test tuple with long elements
Это ошибка, комментарий не соответствует описанию теста

2018-08-23 17:48 UTC, Ranihilator commented on hw_04/include/print.h
> +print_ip (const T arg, bool new_line = true)
2 аргумент, нужен для вставки \n после строки. По умолчанию они вставляются, но в случае работы контейнера или кортежа, для вывода строки нужно иметь возможность вставлять строчку без \n символа.

2018-08-23 17:49 UTC, Ranihilator commented on hw_04/include/print.h
> +print_ip (const T arg, bool is_number = true)
Вывод числа в виде ип адресса, 2 аргумент нужен, для вывода из кортежа или контейнера, чтобы вставлялось число как есть

2018-08-23 17:50 UTC, Ranihilator commented on hw_04/include/print.h
> +    {
Уехала фигурная скобка, это не красиво

2018-08-23 17:52 UTC, Ranihilator commented on hw_04/src/main.cpp
> +using namespace HW_04::PRINT;
Зачем я делаю свой уникальный namespace? Чтобы не было каши в doxygen. Т.к. все домашки находяться в одном репозитории. Ну и естественно цель возможная их объединения в 1 проект.

2018-08-23 17:53 UTC, Ranihilator commented on hw_04/test/test.cpp
> +/*! \file
Отсутствует тесты на проверку отрицательных элементов

2018-08-24 05:37 UTC, Yukigaru requested changes
Хорошая работа. Очень старательно сделаны тесты! Как всегда, есть что подчерпнуть для себя :)

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/CMakeLists.txt
> +    set(VERSION_BUILD $ENV{TRAVIS_BUILD_NUMBER})
а эти переменные где-то нужны, кроме как для project?
можно прямо сюда project положить

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/README.md
> +Application print ip address
отлично! на гитхабе читать приятно )

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +using namespace std;
не рекомендуется.
может стоит рассмотреть вариант одиночных импортов в общий namespace:
using std::decay;
using std::string;
...

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +	static_assert(size > 0, "T must be > 0");
sizeof не может вернуть 0, любой тип занимает минимум 1байт

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +	is_same<typename std::decay<T>::type, string>::value,
а как это сработает для const string?

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +print_ip (const T arg, bool new_line = true)
было бы более универсально не bool new_line, а char endwith.
тогда можно было бы передать ' ' или '\t'

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +	is_same<typename std::decay<T>::type, vector<typename std::decay<T>::type::value_type>>::value ||
довольно большой шаблон, может вынести в отдельный trait?

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +    for (auto i = arg.begin(); i != arg.end(); ++i)
нынче модно использовать std::begin/end :)
хотя в данном случае и так хорошо

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +		if (std::next(i)!=arg.end())
есть вариант сделать это без приращения итератора и избавиться от лишней операции

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/print.h
> +			cout << "..";
но почему ..?

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/tuple.h
> +	\brief specialization for single element
по brief описанию не понятно, что делает этот шаблон

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/tuple.h
> +			buffer << "..";
любая стандартная тулза не поняла бы, что это за .. в ip адресе.
что за прикол =)

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/src/main.cpp
> +    {
тоже съехала скобка )

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/src/main.cpp
> +		print_ip(std::make_tuple(256, "4096", (int64_t)8192, 2048, "128", '5', -256, (int32_t)-1024, -4096, "-8192"));
насколько помню, в ДЗ было условие, что тупл должен быть с одинаковыми типами

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/test/test.cpp
> +		"0\n"
это, конечно, вопрос персональных предпочтений, но на мой взгляд получилось слишком размашисто в угоду codestyle'у

2018-08-24 05:37 UTC, Yukigaru commented on hw_04/include/tuple.h
> +	void operator()(T &arg, stringstream &buffer)
полагаю, тут должен быть const T &

2018-08-24 06:11 UTC, Ranihilator commented on hw_04/CMakeLists.txt
> +    set(VERSION_BUILD $ENV{TRAVIS_BUILD_NUMBER})
Travis автоматически вставляет номер сборки в эти переменные. Удобно получается

2018-08-24 06:11 UTC, Ranihilator commented on hw_04/include/print.h
> +using namespace std;
дай, согласен косяк =), я уже стараюсь так не делаю в последних домашках

2018-08-24 06:12 UTC, Ranihilator commented on hw_04/include/print.h
> +	static_assert(size > 0, "T must be > 0");
ок, если так то уберу.

2018-08-24 06:12 UTC, Ranihilator commented on hw_04/src/main.cpp
> +		print_ip(std::make_tuple(256, "4096", (int64_t)8192, 2048, "128", '5', -256, (int32_t)-1024, -4096, "-8192"));
да так и есть, но я захотел сделать гибридный =)

2018-08-24 06:13 UTC, Ranihilator commented on hw_04/test/test.cpp
> +		"0\n"
подумаю тут другой стиль применить, мне тоже не нравиться.

2018-08-24 06:14 UTC, Ranihilator commented on hw_04/include/tuple.h
> +	void operator()(T &arg, stringstream &buffer)
согласен, проверю этот момент

2018-08-24 06:32 UTC, Yukigaru commented on hw_04/CMakeLists.txt
> +    set(VERSION_BUILD $ENV{TRAVIS_BUILD_NUMBER})
Имел ввиду те, которые ты set'ишь

2018-08-24 09:39 UTC, Ranihilator commented on hw_04/include/tuple.h
> +			buffer << "..";
Наверное, сделаю я все таки одну точку =)

2018-08-24 09:40 UTC, Ranihilator commented on hw_04/include/print.h
> +print_ip (const T arg, bool new_line = true)
хм, хорошая идея, попробую поменять

2018-08-24 09:44 UTC, Ranihilator commented on hw_04/CMakeLists.txt
> +    set(VERSION_BUILD $ENV{TRAVIS_BUILD_NUMBER})
походу кроме проекта, даже незнаю куда их еще можно применить. Покрайнемерее на выхлоп deb файла это влияет.

2018-08-24 09:45 UTC, Ranihilator commented on hw_04/include/print.h
> +	is_same<typename std::decay<T>::type, string>::value,
походу не сработает, проверю и поправлю

2018-08-24 09:46 UTC, Ranihilator commented on hw_04/include/print.h
> +	is_same<typename std::decay<T>::type, vector<typename std::decay<T>::type::value_type>>::value ||
Можно вынести, почему бы и нет

2018-08-24 09:48 UTC, Ranihilator commented on hw_04/include/print.h
> +    for (auto i = arg.begin(); i != arg.end(); ++i)
из за необходимости итератора это сделал

2018-08-24 09:48 UTC, Ranihilator commented on hw_04/include/print.h
> +		if (std::next(i)!=arg.end())
подумаю над решением

2018-08-24 09:48 UTC, Ranihilator commented on hw_04/include/print.h
> +			cout << "..";
будет одна =)

2018-08-27 15:54 UTC, Ranihilator commented on hw_04/include/tuple.h
> +{
попробую покрутить index_sequence

2018-08-27 15:55 UTC, Ranihilator commented on hw_04/test/test.cpp
> +		"256..4096..8192..2048..128..-1..-256..-1024..-4096..-8192\n"
Сделаю с "."

2018-08-27 16:28 UTC, Ranihilator commented on hw_04/include/print.h
> +using namespace std;
исправил

2018-08-27 17:07 UTC, Ranihilator commented on hw_04/include/print.h
> +	is_same<typename std::decay<T>::type, string>::value,
проверил, срабатывает

2018-08-27 17:09 UTC, Ranihilator commented on hw_04/include/tuple.h
> +	void operator()(T &arg, stringstream &buffer)
исправил

2018-08-27 18:06 UTC, antik9 requested changes
Ok

2018-08-27 18:06 UTC, antik9 approved these changes

2018-08-27 18:55 UTC, Yukigaru approved these changes
Аппрув :)

2018-08-28 02:20 UTC, merged